<?xml version="1.0"?>
<package format="2">
  <name>mpc_controller</name>
  <version>0.1.0</version>
  <description>Model Predictive Controller for Baxter robot joint-space trajectory planning using CasADi/IPOPT</description>

  <maintainer email="gentritfejza@gmail.com">Gentrit Fejza</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>baxter_kinematics</depend>
  <depend>baxter_core_msgs</depend>
  <depend>baxter_interface_cpp</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>dynamic_reconfigure</depend>

  <export>
  </export>
</package>
